version: '3.7'

services:
  database:
    container_name: duit_bff_local_db
    image: postgres:latest
    ports:
      - 5432:5432
    # volumes:
    #   - .:/data/db
    restart: on-failure
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file: .env
